# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: sonic-mgmt-common
    type: github
    name: Azure/sonic-mgmt-common
    endpoint: build

stages:
- stage: Build
  jobs:
  - job:
    displayName: "build"
    timeoutInMinutes: 60

    pool:
      vmImage: ubuntu-20.04

    container:
      image: sonicdev-microsoft.azurecr.io:443/sonic-slave-buster:latest

    steps:
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'

    - checkout: sonic-mgmt-common
      clean: true
      submodules: recursive
      displayName: 'Checkout code'

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: build
        pipeline: 1
        artifact: sonic-buildimage.vs
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/master'
      displayName: "Download sonic buildimage"

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: build
        pipeline: 127
        artifact: sonic-mgmt-common
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/master'
      displayName: "Download sonic-mgmt-common"

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: build
        pipeline: 169
        artifact: golang
        runVersion: 'latestFromBranch'
        targetPath: '$(Build.ArtifactStagingDirectory)/golang'
        runBranch: 'refs/heads/main'
      displayName: "Download golang"

    - script: |
        # REDIS
        sudo apt-get install -y redis-server
        sudo sed -ri 's/^# unixsocket/unixsocket/' /etc/redis/redis.conf
        sudo sed -ri 's/^unixsocketperm .../unixsocketperm 777/' /etc/redis/redis.conf
        sudo sed -ri 's/redis-server.sock/redis.sock/' /etc/redis/redis.conf
        sudo service redis-server start

        # LIBYANG
        sudo dpkg -i ../target/debs/buster/libyang*1.0.73*.deb
      displayName: "Install dependency"

    - script: |
        cd $(Build.ArtifactStagingDirectory)/golang/openssl
        sudo dpkg -i --force-overwrite libssl1.1_1.1.1g-fips_amd64.deb libssl-dev_1.1.1g-fips_amd64.deb openssl_1.1.1g-fips_amd64.deb libssl-doc_1.1.1g-fips_all.deb
        cd $(Build.ArtifactStagingDirectory)/golang/
        sudo dpkg -i --force-overwrite golang-1.14-go_1.14-3~fips_amd64.deb golang-1.14_1.14-3~fips_all.deb golang-1.14-doc_1.14-3~fips_all.deb
      displayName: "Install golang"

    - script: |
        set -ex
        ls -l

        pushd sonic-mgmt-common

        NO_TEST_BINS=1 dpkg-buildpackage -rfakeroot -b -us -uc

        popd

        pushd sonic-telemetry

        dpkg-buildpackage -rfakeroot -us -uc -b -j$(nproc) && cp ../*.deb $(Build.ArtifactStagingDirectory)/
      displayName: "Build"

    - publish: $(Build.ArtifactStagingDirectory)/
      artifact: sonic-telemetry
      displayName: "Archive artifacts"

